import Head from "next/head";
import style from "@/styles/Home.module.scss";
import Header from "@/components/Molecules/Header/Header";
import WindowBox from "@/components/Organism/Window/WindowBox";
import InputBox from "@/components/Molecules/InputBox/InputBox";
import { useState } from "react";
import SelectBox from "@/components/Molecules/SelectBox/SelectBox";
import { genreList } from "@/constants/common";
import Button from "@/components/Atoms/Button/Button";
import Carousel from "@/components/Molecules/Carousel/Carousel";
import Switch from "@/components/Atoms/Switch/Switch";
import Toast from "@/components/Atoms/Toast/Toast";

export default function Home() {
  const [protagonist, setProtagonist] = useState("");
  const [antagonist, setAntagonist] = useState("");
  const [genre, setGenre] = useState("");
  const [pagi18, setPagi18] = useState(false);
  const [error, setError] = useState(false);
  const [loading, setLoading] = useState(false);
  const [response, setResponse] = useState("");
  const [stories, setStories] = useState<string[]>([]);
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentIndex, setCurrentIndex] = useState(0);

  const handleGenerate = async () => {
    setLoading(true);
    setError(false);

    const prompt = `Generate an ${genre} story for ${pagi18 ? "adults" : "children"
      }, with ${protagonist} as protagonist and ${antagonist} as antagonist`;

    //controlliamo se esiste
    if (process.env.NEXT_PUBLIC_GEMINI_KEY) {
      // se esiste crea istanza
      const genAI = new GoogleGenerativeAI(process.env.NEXT_PUBLIC_GEMINI_KEY);
      // decidi modello da utilizzare
      const model = genAI.getGenerativeModel({ model: "gemini-3.5-flash-lite" });
      // passa promot
      const result = await model.generateContent(prompt);
      console.log(result);

      const output = (
        result.response.candidates as GenerateContentCandidate[]
      )[0].content.parts[0].text;
      console.log("Output generato:", output);

      if (output) {
        setResponse(output);
      }
    }
  };

  return (
    <>
      <Head>
        <title>AI Story Teller</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={style.main}>
        <Header title={"AI Story Teller"} />
        <div className={style.content}>
          {error && (
            <Toast
              setAction={setError}
              title="Error"
              message="Error creating the story"
            />
          )}
          <WindowBox title="Story Params">
            <div className={style.container}>
              <InputBox
                label={"Protagonist's name"}
                value={protagonist}
                setValue={setProtagonist}
              />
              <InputBox
                label={"Antagonist's name"}
                value={antagonist}
                setValue={setAntagonist}
              />
              <SelectBox label="Genre:" list={genreList} setAction={setGenre} />
              <Switch active={pagi18} setActive={setPagi18} />
              <Button
                label="Generate"
                onClick={handleGenerate}
                disabled={
                  protagonist.trim().length <= 0 ||
                  antagonist.trim().length <= 0 ||
                  genre.trim().length <= 0 ||
                  loading
                }
              />
            </div>
            {error && <p>errore nella generazione</p>}
            {loading && (
              <div className={style.loading}>
                <p>loading...</p>
              </div>
            )}
            {!loading && response && (
              <div className={style.result}>
                <div className={style.btn}>
                  {isPlaying ? (
                    <Button label="Stop Story" onClick={handleStopVoice} />
                  ) : (
                    <Button label="Play Story" onClick={handleVoice} />
                  )}
                </div>
                {response}
              </div>
            )}
          </WindowBox>
        </div>

        {!loading && stories.length > 0 && (
          <Carousel
            stories={stories}
            currentIndex={currentIndex}
            setCurrentIndex={setCurrentIndex}
          />
        )}
      </main>
    </>
  );
}
